### ISSUE TITLE
Backend : user login and sign up page with google auth 

### ISSUE THREAD

**Issue by otakuparshva** [otakuparshva/Platformer-game-website---2nd-year-internship-project-#15]
# Backend Logic for Login and Sign Up with Google Auth in Django

## Description
Create the backend logic for the login and sign up pages, including Google authentication, using Django. There is no need to work on the database for this task.

## Requirements
- Implement backend logic for user login.
- Implement backend logic for user sign up.
- Integrate Google authentication.
- Structure the code within one Django app named `user`.

## Folder Structure

project-root/
└── user/
├── init.py
├── admin.py
├── apps.py
├── models.py
├── tests.py
├── urls.py
├── views.py
├── google_auth.py
└── ...

## Acceptance Criteria
- [ ] Users should be able to log in with their credentials.
- [ ] Users should be able to sign up with their details.
- [ ] Users should be able to log in/sign up using Google authentication.
- [ ] All logic should reside within the `user` Django app.

## Implementation Details
- Use Django's built-in authentication system for login and sign up.
- Use `django-allauth` or similar package for Google authentication.
- Ensure the views are connected via `urls.py` within the `user` app.
- Follow Django's best practices for structuring the views and handling authentication.

## Additional Notes
- Ensure the code is clean and well-documented.
- Follow the existing project conventions and style guides.
- Add any necessary middleware or settings for Google authentication.
- Focus on the logic only; database interactions are not required.

## References
- [Django Authentication Documentation](https://docs.djangoproject.com/en/stable/topics/auth/)
- [django-allauth Documentation](https://django-allauth.readthedocs.io/en/latest/installation.html)
- [Google Authentication Documentation](https://developers.google.com/identity/sign-in/web/sign-in)

**Comment by hardii444** [comment]
working on #15

**Comment by hardii444** [comment]
work done #15
