### ISSUE TITLE
game : do game setup with background 

### ISSUE THREAD

**Issue by otakuparshva** [otakuparshva/Platformer-game-website---2nd-year-internship-project-#20]
**Title:** Setup Pygame Platformer Project and Implement Background

**Description:**

This feature request outlines the initial steps for setting up a Pygame project specifically designed for a platformer game. Additionally, it covers the process of adding a background image to establish the visual environment.

**Tasks:**

1. **Project Setup:**
    - Create a new project directory with a descriptive name (e.g., `platformer_game`).
    - Consider creating subdirectories for potential future needs (e.g., `images`, `sounds`, `levels`).

2. **Pygame Installation:**
    - Ensure Pygame is installed within your development environment (instructions can be found online). 

3. **Python Script Creation:**
    - Create a Python script named `game.py` within the project directory. This script will house the core game logic and Pygame functionalities.

4. **Background Image Integration:**
    - Prepare a background image (`background.png`) that aligns with your desired game world aesthetics.
    - This image should be placed in the same directory as `game.py`.

**Next Steps:**

- This initial setup provides a foundation for building a platformer game. 
- After addressing this issue, we can move forward with implementing player movement, game mechanics, and other platformer essentials.

**Labels:**

* Apply relevant labels (e.g., "pygame", "platformer", "background") to categorize this issue for better tracking.

**Additional Notes:**

- Background image size can be adjusted to fit your game window resolution.
- Explore tiled backgrounds for larger game worlds as needed.

By following these steps and collaborating, we can establish a solid foundation for your platformer project!

**Comment by Meet-GU** [comment]
working on #20

**Comment by Meet-GU** [comment]
Completed # 20

**Comment by Meet-GU** [comment]
completed #20
